version: '3.8'

services:
  node1:
    build: .
    environment:
      LOAD_BALANCER_URL: http://host.docker.internal:8080/register
      SERVER_PORT: 5000
      SERVER_IP: 127.0.0.1
    ports:
      - "5000:5000"
    container_name: node1
    restart: always

  node2:
    build: .
    environment:
      LOAD_BALANCER_URL: http://host.docker.internal:8080/register
      SERVER_PORT: 5001
      SERVER_IP: 127.0.0.1
    ports:
      - "5001:5001"
    container_name: node2
    restart: always

  node3:
    build: .
    environment:
      LOAD_BALANCER_URL: http://host.docker.internal:8080/register
      SERVER_PORT: 5002
      SERVER_IP: 127.0.0.1
    ports:
      - "5002:5002"
    container_name: node3
    restart: always
